language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "1.8"
  - "2.5"
  - "3.3"
  - "4.9"
  - "5.12"
  - "6.17"
  - "7.10"
  - "8.16"
  - "9.11"
  - "10.15"
  - "11.15"
  - "12.3"
os:
  - linux
  - windows
before_install:
  # Configure npm
  - |
    # Skip updating unsafe-perm / false
    npm config set unsafe-perm true
install:
  - npm install protoc-gen-grpc -g
script:
  # Run test script
  - npm run test-js-out
  - npm run test-ts-out
