language: node_js
node_js:
  - '10'
  - '8'
  - '6'
  - '4'
os:
  - linux
  - windows
before_install:
  # Configure npm
  - |
    # Skip updating unsafe-perm / false
    npm config set unsafe-perm true
script:
  # Run test script
  - npm run test-js-out
  - npm run test-ts-out
